---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time={{apt_cache_timeout}}
  tags: bootstrap

- name: Apt install required system packages.
  apt: pkg={{item}} state=installed
  tags: bootstrap
  with_items:
    - zookeeper
    - zookeeperd

- name: Setup myid file.
  template: src=myid.j2 dest=/etc/zookeeper/conf/myid
  notify:
    - restart zookeeper
  tags: deploy

- name: Setup default config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  notify:
    - restart zookeeper
  tags: deploy

- meta: flush_handlers

- name: Enable Zookeeper
  service: name=zookeeper state=started enabled=yes

- name: Wait for Zookeeper port
  wait_for: port={{ zookeeper_client_port }} state=started timeout=30
