---
- name: start zookeeper
  service: name=zookeeper state=started

- name: stop zookeeper
  service: name=zookeeper state=stopped

- name: restart zookeeper
  service: name=zookeeper state=restarted

- name: restart consul 
  supervisorctl: name=consul state=restarted

# Note: Not all configuration changes get reloaded:
# https://www.consul.io/docs/agent/options.html#reloadable-configuration
- name: reload consul 
  command: name={{ zookeeper_consul_bin_dir }}/consul reload 
