---
- name: start zookeeper
  service: name=zookeeper state=started

- name: stop zookeeper
  service: name=zookeeper state=stopped

- name: restart zookeeper
  service: name=zookeeper state=restarted

- name: restart consul 
  service: name=consul state=restarted
